# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: 414040138@qq.com
name: Lomo # 姓名，将会在首页显示
description: > # this means to ignore newlines until "baseurl:"
  我的站点还在写。。就是这样
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lomoy.github.io" # the base hostname & protocol for your site
github_username:  lomoY
sina_weibo: http://weibo.com/p/1005052598417474/home?from=page_100505&mod=TAB&is_all=1#place
lofter: http://frontlomo.lofter.com
flickr: https://www.flickr.com/photos/142560832@N07/?
# Build settings
markdown: kramdown
encoding: utf-8

# Sass settings
sass:
  sass_dir: _sass
  style: compressed