# Site settings
email: 414040138@qq.com
name: Lomo # 姓名，将会在首页显示
description:  # this means to ignore newlines until "baseurl:"
  站点建设中
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lomoy.github.io" # the base hostname & protocol for your site
github_username:  lomoY
sina_weibo: http://weibo.com/p/1005052598417474/home?from=page_100505&mod=TAB&is_all=1#place
lofter: http://frontlomo.lofter.com
flickr: https://www.flickr.com/photos/142560832@N07/?
# Build settings
markdown: kramdown
encoding: utf-8

# Sass settings
sass:
  sass_dir: _sass
  style: compressed
#这个到底是啥。。  
include:
  - .htaccess
  - _pages

defaults:
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

  # Blog Articles
  - scope:
      path: _posts/article
      type: posts
    values:
      layout: article
      category: article
      breadcrumbs:
        - label: "Blog Article"
          url: /article/